# CCN Python Workshop

This is a introduction of Python language using Jupyter Notebook. We'll learn some basics of Python version 3.0, especially the data structures in Python!

### Get Jupyter Notebook

#### Methord 1:
Install to your laptop using Anaconda:

https://jupyter.org/install

Download Anaconda 3.7 version, install to your Macbook, then run "jupyter notebook"

#### Methord 2:
Run on Hoffman2

https://www.hoffman2.idre.ucla.edu/access/jupyter-notebook/

Download h2jupynb from

https://gitlab.idre.ucla.edu/dauria/jupyter-notebook

chmod u+x h2jupynb

from your laptop, run the following command to use Python 3.7

```bash
./h2jupynb -u userid -v 3.7.0
```
Replace the userid with your Hoffman user ID

### Variables

In [1]:
#comments
#Variable name can use [a-z,A-Z,0-9,”_”] but not starts with a number
#No need to pre-define variables but it's a good practice to initialize them
a = 5
b = 3
c = a + b
print(c)

8


In [3]:
#c = 0
c += 1  ##same as c = c + 1 
print(c)

1


In [4]:
input_num = input("give me a number ")

print(type(input_num))

input_num += 1

give me a number 7
<class 'str'>


TypeError: must be str, not int

In [5]:
##use int() to convert to int type
print(int(input_num) + 1)

8


In [6]:
## Integer and floating-point division:
print(7/2) # int/int returns int in python ver2.x!
print(7/2.0)
print(7.0/2)
print(7/float(2))

print(7.0//2) # floor (truncate)

print(7%3)  # remainder

print(10**3) # exponent


3.5
3.5
3.5
3.5
3.0
1
1000


### Strings

In [19]:
empty_string = ""
first_string = "Neural Imaging"
print(first_string)
print(len(first_string))

Neural Imaging
14


In [8]:
##use index to access individual characters 
print(first_string[0])
print(first_string[1])
print(first_string[2])

N
e
u


In [9]:
##slicing
print(first_string[0:5])  ##[5] is not included
print(first_string[-1])   ##last character

Neura
g


In [12]:
##Single quotation works too
second_string = 'single quotation'
print(second_string)
#Concatenation
new_string = second_string + ' works too!' + "!"
print(new_string)

single quotation
single quotation works too!!


In [16]:
##split a string
third_string = "Jane M Bruin"
firstname,middle,lastname = third_string.split(' ')
print ("first name:", firstname.lower())
print ("middle name:", middle)
print ("last name:", lastname.upper())

first name: jane
middle name: M
last name: BRUIN


### List

In [20]:
### A list formed with numbers
list_n = [1,2,3,5,7,11]
print(list_n)
print("length is: ", len(list_n))

[1, 2, 3, 5, 7, 11]
length is:  6


In [21]:
### A list formed with Strings
list_c = ["Python","C++","Java","Ruby"]
print(list_c)
print("length: ", len(list_c))

['Python', 'C++', 'Java', 'Ruby']
length:  4


In [24]:
### A mixed-typed list
list_mix = ["sunny",30, 70,0.25]
print(type(list_mix))
print(list_mix)

<class 'list'>
['sunny', 30, 70, 0.25]


In [25]:
###generate an empty list
list_empty = []

##add items to the list
list_empty.append(1)
print(list_empty)

list_empty.append(2)
print(list_empty)

[1]
[1, 2]


In [26]:
list_num = [1,2,3,4,5,6,7,8,9]
print(list_num) 

##access elements by indexes
first_item = list_num[0]
print(first_item)

second_item = list_num[7]
print(second_item)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
1
8


In [27]:
##List is mutable
##change second item
list_num[1] = 1
list_num[7] = 5
print(list_num) 

[1, 1, 3, 4, 5, 6, 7, 5, 9]


In [28]:
##list.remove removes the first matching element
list_num.remove(5)
print(list_num)

[1, 1, 3, 4, 6, 7, 5, 9]


In [29]:
##insert 5 at index 3
list_num.insert(3,5)
print(list_num)

[1, 1, 3, 5, 4, 6, 7, 5, 9]


In [30]:
##pop removes the last element from list
last=list_num.pop()
print(last)
print(list_num)

9
[1, 1, 3, 5, 4, 6, 7, 5]


In [31]:
###When pop() takes a index, it delete the item with that index
third = list_num.pop(3)
print(third)
print(list_num)

5
[1, 1, 3, 4, 6, 7, 5]


In [32]:
##del can be used to delete by index
del list_num[2:4]
print(list_num)

[1, 1, 6, 7, 5]


In [ ]:
###slicing of the list (return a new list)
alist[start:stop:step]
alist[start:stop]  #items from start to stop-1 position
alist[start:]      #items from start position to the end
alist[:stop]       #items from beginning to stop-1 position
alist[:]           #all items
alist[-1]          #last item
alist[-2]          #second last item
alist[-2:]         #second last itme to the end

In [33]:
##Generate a list by loop
numbers = []
for i in range (0,20):
    numbers.append(i)
numbers    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [35]:
print("numbers[1:9]", numbers[1:9])
print("numbers[1:9:2]",numbers[1:9:2])
print("numbers[11:]",numbers[11:])
print("numbers[:5]",numbers[:5])
print("numbers[:]", numbers[:])
print("numbers[-1]", numbers[-1])
print("numbers[-2]", numbers[-2])
print("numbers[-2:]", numbers[-2::-1])

numbers[1:9] [1, 2, 3, 4, 5, 6, 7, 8]
numbers[1:9:2] [1, 3, 5, 7]
numbers[11:] [11, 12, 13, 14, 15, 16, 17, 18, 19]
numbers[:5] [0, 1, 2, 3, 4]
numbers[:] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
numbers[-1] 19
numbers[-2] 18
numbers[-2:] [18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [36]:
###concatenating lists
list_con1 = [1, 2, 3]
list_con2 = [4, 5, 6, 7]
list_con = list_con1 + list_con2
print(list_con)

[1, 2, 3, 4, 5, 6, 7]


### Tuple

In [37]:
##A tuple consists of a number of values separated by commas (between parentheses)
tuple_num = (1,2,3,4,5)
tuple_mon = ("January","February","March")
tuple_mix = (1,"Jan","12:45",30)
print(tuple_num)
print(tuple_mon)
print(tuple_mix)

(1, 2, 3, 4, 5)
('January', 'February', 'March')
(1, 'Jan', '12:45', 30)


In [38]:
##tuple is immutable (when it does not contain mutable items)
tuple_num[1] = 3

TypeError: 'tuple' object does not support item assignment

### Dictionary

In [39]:
##Key-Value pairs separated by colon(keys are unique), between curly braces
months = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May':5}
months['June'] = 6
print(months['March'])

print(months)

3
{'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6}


In [41]:
##print all the keys
for m in months:
    print(m)

## use "in" to check if a key exists
if 'July' in months:
    print("July exists already")
else:
    months['July'] = 7
    
print(months)    


January
February
March
April
May
June
July
July exists already
{'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 'July': 7}


In [42]:
##Other ways to get keys, values or the key-value pair
print(months.keys())
print(months.values())
print(months.items())

dict_keys(['January', 'February', 'March', 'April', 'May', 'June', 'July'])
dict_values([1, 2, 3, 4, 5, 6, 7])
dict_items([('January', 1), ('February', 2), ('March', 3), ('April', 4), ('May', 5), ('June', 6), ('July', 7)])


In [43]:
for key,val in months.items():
    print(key, " - ", val)

January  -  1
February  -  2
March  -  3
April  -  4
May  -  5
June  -  6
July  -  7


In [ ]:
##more complicated dictionaries
contacts = {'001':['Haiyan', 'haiyanwang@mednet.ucla.edu','Semel']}
contacts ['002'] = ['Mary', 'mary@g.ucla.edu', 'Semel']
contacts

### Conditional Statements

In [44]:
##compare numbers
n = 5
m = 3
if n > m:
    print ("n is larger")
elif n == m:
    print ("n is equal to m")
else:
    print ("n is smaller")

##compare strings
name = "CCN"
if name == "CCN":
    print("CCN")
else:
    print("Not CCN")


n is larger
CCN


### Loop

In [45]:
##for loop
for i in range(5):
    print(i)

0
1
2
3
4


In [46]:
for j in range(4,8):
    print(j)

4
5
6
7


In [47]:
for k in range(1,10,2):
    print(k)

1
3
5
7
9


In [48]:
##loop through a list
folders = ["func", "dwi", "anat", "fmap"]
for folder in folders:
    print(folder)

func
dwi
anat
fmap


In [ ]:
##loop through a set
for s in set1:
    print(s)

In [49]:
##loop through a dictionary
for k,v in (months.items()):
    print (k, ": ", v)

January :  1
February :  2
March :  3
April :  4
May :  5
June :  6
July :  7


In [50]:
for index, item in enumerate(folders):
    print(index, item)

0 func
1 dwi
2 anat
3 fmap


In [51]:
##While loop
n = 0
while(n < 10):
    print(n)
    n += 1

0
1
2
3
4
5
6
7
8
9


In [52]:
##break the loop
n = 0
while(True):
    print(n)
    if n==4:
        break
    n += 1

0
1
2
3
4


In [53]:
##continue: skip loops at certain condition
for n in range(0,10):
    if n%2==0:
        continue
    print(n)

1
3
5
7
9


### Functions

In [54]:
##funciton without parameters
def hello(): 
    print("Hello World!")

##call hello function
hello()

Hello World!


In [55]:
##function with parameters
def getPow(n):
    return n ** 2

##call double function
print(getPow(5))

25


In [56]:
##parameters can have default values
def printNumbers(start=0, end=3):
    
    if start >= end:
        print("end need to be larger than start")
    else:
        for i in range(start, end):
            print(i)

##call without parameters
print("Print numbers without parameters:")
printNumbers()

##call with parameters
print("Print numbers with parameters as (2,5):")
printNumbers(2,5)

Print numbers without parameters:
0
1
2
Print numbers with parameters as (2,5):
2
3
4


In [ ]:
##count how many times a word shown using dictionary
def count_words(s):
    
    word_dict = {}
    for k in s.lower().split(' '):
        if k in word_dict:
            word_dict[k]+=1
        else:
            word_dict[k]=1
    return word_dict

print(count_words("oh what a day what a lovely day"))

### Numpy

In [58]:
##import numpy library
import numpy as np

In [59]:
zero_arr = np.array([[0,0,0],
                     [0,0,0]])
print(zero_arr)
print(zero_arr.shape)

[[0 0 0]
 [0 0 0]]
(2, 3)


In [60]:
zero_arr2 = np.zeros(shape=(3, 1))
print(zero_arr2)
ones_arr = np.ones(shape=(3, 2))
print(ones_arr)

[[0.]
 [0.]
 [0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [61]:
random_arr = np.random.randn(3, 3)
print(random_arr)

[[ 2.35741771 -0.6008627   0.80660342]
 [-1.06119617 -1.41934966 -0.40971739]
 [-1.28700607 -1.28326391 -0.3783107 ]]


In [62]:
##find the shape
print(random_arr.shape)

(3, 3)


In [63]:
##access by index
print(random_arr[1,0])

-1.0611961718062264


In [64]:
##access by slicing
##third row
print("third row", random_arr[2,:])
##second column
print("second column",random_arr[:,1])
print(random_arr[0:2,0:2])

third row [-1.28700607 -1.28326391 -0.3783107 ]
second column [-0.6008627  -1.41934966 -1.28326391]
[[ 2.35741771 -0.6008627 ]
 [-1.06119617 -1.41934966]]


In [65]:
##inner (dot) production of vectors
arr_a = np.array([1,2,3])
arr_b = np.array([3,2,1])
inner_prod = np.dot(arr_a,arr_b)
print(inner_prod)

##element wise production
element_prod = np.multiply(arr_a,arr_b)
print(element_prod)

##sum of vector
npsum = np.sum([1,2,3])
print(npsum)

10
[3 4 3]
6
